import { useState } from 'react';
import './CommonWorkspace.css';
import './BlockchainFlow.css';

const people = [
  { name: 'Arjun Sharma', employee: 'BEL-001', role: 'Admin', department: 'Defence Systems', state: 'Active' },
  { name: 'Priya Nair', employee: 'BEL-002', role: 'Manager', department: 'Procurement', state: 'Active' },
  { name: 'Kiran Mehta', employee: 'BEL-003', role: 'Auditor', department: 'Audit & Compliance', state: 'Active' },
  { name: 'Rahul Gupta', employee: 'BEL-004', role: 'User', department: 'Electronics', state: 'Active' },
  { name: 'Sita Reddy', employee: 'BEL-005', role: 'User', department: 'R&D', state: 'Active' },
  { name: 'Dev Kapoor', employee: 'BEL-006', role: 'Manager', department: 'IT Security', state: 'Inactive' },
];

const initialAssets = [
  { id: 'ASSET-001', name: 'Radar Control Module MK-IV', category: 'Defence Equipment', sensitivity: 'Critical', owner: 'Arjun Sharma', state: 'Active' },
  { id: 'ASSET-002', name: 'Encrypted Communications Device', category: 'Device', sensitivity: 'High', owner: 'Priya Nair', state: 'Active' },
  { id: 'ASSET-003', name: 'Q3 Procurement Clearance Doc', category: 'Enterprise Document', sensitivity: 'High', owner: 'Priya Nair', state: 'Active' },
  { id: 'ASSET-004', name: 'ISO 27001 Certification', category: 'Certificate', sensitivity: 'Medium', owner: 'Arjun Sharma', state: 'Active' },
  { id: 'ASSET-005', name: 'ERP Suite License', category: 'Software License', sensitivity: 'Medium', owner: 'Dev Kapoor', state: 'Pending' },
  { id: 'ASSET-006', name: 'Missile Guidance Subsystem', category: 'Defence Equipment', sensitivity: 'Critical', owner: 'Arjun Sharma', state: 'Active' },
];

const initialRequests = [
  { id: 'REQ-021', requester: 'Rahul Gupta', asset: 'Radar Control Module MK-IV', action: 'View', duration: '8 hours', risk: 'High', status: 'Pending' },
  { id: 'REQ-022', requester: 'Sita Reddy', asset: 'Missile Guidance Subsystem', action: 'Read', duration: '4 hours', risk: 'Critical', status: 'Pending' },
  { id: 'REQ-019', requester: 'Rahul Gupta', asset: 'ISO 27001 Certification', action: 'Download', duration: '2 hours', risk: 'Low', status: 'Approved' },
  { id: 'REQ-018', requester: 'Sita Reddy', asset: 'Encrypted Communications Device', action: 'Modify', duration: '1 day', risk: 'High', status: 'Denied' },
];

const initialPermissions = [
  { id: 'PERM-001', user: 'Priya Nair', role: 'Manager', asset: 'Radar Control Module MK-IV', permission: 'View', status: 'Active', grantedBy: 'Arjun Sharma', until: '29 Oct 2026' },
  { id: 'PERM-002', user: 'Rahul Gupta', role: 'User', asset: 'Encrypted Communications Device', permission: 'View', status: 'Revoked', grantedBy: 'Priya Nair', until: '29 Sep 2026' },
  { id: 'PERM-003', user: 'Kiran Mehta', role: 'Auditor', asset: 'Missile Guidance Subsystem', permission: 'View', status: 'Active', grantedBy: 'Arjun Sharma', until: '28 Nov 2026' },
];

const auditEvents = [
  ['Identity Created', 'Arjun Sharma', 'Verified identity profile created', 'Success', '25 Sept 2026, 08:16 pm', '◉'],
  ['Asset Registered', 'Arjun Sharma', 'Radar Control Module MK-IV', 'Success', '27 Sept 2026, 10:16 pm', '◈'],
  ['Asset Allocated', 'Priya Nair', 'Encrypted Communications Device', 'Success', '28 Sept 2026, 09:36 pm', '◈'],
  ['Access Granted', 'Priya Nair', 'Q3 Procurement Clearance Doc', 'Success', '29 Sept 2026, 09:16 am', '◆'],
  ['Permission Updated', 'Arjun Sharma', 'Controlled permission record', 'Success', '29 Sept 2026, 12:56 pm', '◆'],
  ['Access Review Required', 'Security review', 'A controlled action needs review', 'Failed', '29 Sept 2026, 05:56 pm', '△'],
];

const stages = ['Created', 'NFT Minted', 'Assigned', 'Access Granted', 'Permission Updated', 'Transferred', 'Current Owner'];
const safeReference = (value) => value.replace(/[^A-Z0-9]/gi, '').slice(-3).padStart(3, '0');

function Glyph({ children }) { return <span className="common-glyph" aria-hidden="true">{children}</span>; }
function Button({ children, className = '', ...props }) { return <button type="button" className={`common-button ${className}`} {...props}>{children}</button>; }
function Pill({ children, tone = '' }) { return <span className={`common-pill ${tone}`}>{children}</span>; }
function Modal({ title, children, onClose }) { return <div className="common-modal-backdrop" role="presentation" onMouseDown={onClose}><section className="common-modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(event) => event.stopPropagation()}><header><h2>{title}</h2><button type="button" onClick={onClose} aria-label="Close dialog">×</button></header>{children}</section></div>; }
function PageHead({ eyebrow, title, children, action }) { return <div className="common-page-head"><div><p>{eyebrow}</p><h1>{title}</h1>{children && <div className="common-subtitle">{children}</div>}</div>{action}</div>; }
function EmptyDetails({ icon = '⌁', children }) { return <aside className="common-empty"><Glyph>{icon}</Glyph><p>{children}</p></aside>; }

function IdentityPage({ notify }) {
  const [selected, setSelected] = useState(0); const [create, setCreate] = useState(false); const [form, setForm] = useState({ name: '', employee: '', department: '', credential: '' });
  const person = people[selected];
  const createDid = (event) => { event.preventDefault(); setCreate(false); notify(`Identity profile for ${form.name || 'new employee'} created and queued for protected verification.`); };
  return <div className="common-workspace"><PageHead eyebrow="IDENTITY MANAGEMENT" title="Identity Management" action={<Button className="primary" onClick={() => setCreate(true)}><Glyph>＋</Glyph>Create DID</Button>}>Manage and verify decentralized identities without exposing protected identifiers.</PageHead><div className="identity-grid"><section className="common-card identity-list"><h3>Select identity</h3>{people.map((item, index) => <button type="button" onClick={() => setSelected(index)} className={selected === index ? 'selected' : ''} key={item.employee}><span className="initial">{item.name[0]}</span><span><b>{item.name}</b><small>{item.employee}</small></span><em>{index === 4 ? '◷' : '✓'}</em></button>)}</section><div className="identity-details"><section className="common-card identity-person"><div className="identity-heading"><span className="large-initial">{person.name[0]}</span><div><h2>{person.name}</h2><p>{person.department} · {person.employee}</p><Pill tone="success">Verified</Pill> <Pill>{person.role}</Pill></div></div><div className="fact-grid"><div><small>Employee ID</small><b>{person.employee}</b></div><div><small>Department</small><b>{person.department}</b></div><div><small>Role</small><b>{person.role}</b></div><div><small>Status</small><b>{person.state}</b></div><div><small>Credential proof</small><b>Protected reference</b></div><div><small>Joined</small><b>2024-01-15</b></div></div></section><section className="common-card protected-proof"><h3><Glyph>♙</Glyph>Identity verification</h3><pre>{`// Decentralized Identifier Document\nidentity      ${person.employee}\nverification  VERIFIED\ncontroller    protected backend record\ncreated       2024-01-15\nproof type    signed enterprise credential`}</pre></section><section className="common-card history-card"><h3>Identity change history</h3><div className="mini-event"><i />Identity Created <span>by Arjun Sharma</span><small>25/09/2026</small></div></section></div></div>{create && <Modal title="Create New DID" onClose={() => setCreate(false)}><form className="common-form" onSubmit={createDid}><label>Full name<input required placeholder="Enter full name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Employee ID<input required placeholder="Enter employee ID" value={form.employee} onChange={(e) => setForm({ ...form, employee: e.target.value })} /></label><label>Department<input required placeholder="Enter department" value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} /></label><label>Credential reference<input required placeholder="Protected credential reference" value={form.credential} onChange={(e) => setForm({ ...form, credential: e.target.value })} /></label><footer><Button onClick={() => setCreate(false)}>Cancel</Button><Button className="primary" type="submit">Create DID</Button></footer></form></Modal>}</div>;
}

function UsersPage() {
  const [role, setRole] = useState('All'); const [selected, setSelected] = useState(null); const filtered = role === 'All' ? people : people.filter((person) => person.role === role);
  return <div className="common-workspace"><PageHead eyebrow="ROLE-BASED ACCESS CONTROL" title="Users & Roles" action={<div className="filter-buttons">{['All', 'Admin', 'Manager', 'Auditor', 'User'].map((item) => <Button key={item} className={role === item ? 'active' : ''} onClick={() => setRole(item)}>{item}</Button>)}</div>}>Manage enterprise users and RBAC role assignments.</PageHead><div className="role-stats">{['Admin', 'Manager', 'Auditor', 'User'].map((item) => <section className="common-card" key={item}><Pill tone={item.toLowerCase()}>{item}</Pill><strong>{people.filter((person) => person.role === item).length}</strong><small>users assigned</small></section>)}</div><div className="two-panel"><section className="common-card table-card"><table className="common-table"><thead><tr><th>Employee</th><th>Department</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((person) => <tr key={person.employee}><td><span className="avatar">{person.name[0]}</span><b>{person.name}</b><small>{person.employee}</small></td><td>{person.department}</td><td><Pill tone={person.role.toLowerCase()}>{person.role}</Pill></td><td><Pill tone={person.state === 'Active' ? 'success' : ''}>{person.state}</Pill></td><td><Button className="icon-button" onClick={() => setSelected(person)}>♧</Button></td></tr>)}</tbody></table></section>{selected ? <section className="common-card selected-detail"><h3>{selected.name}</h3><p>{selected.employee} · {selected.department}</p><Pill tone={selected.role.toLowerCase()}>{selected.role}</Pill><hr /><b>Assigned role capabilities</b><ul><li>Authorised workspace access</li><li>Role-level data filtering</li><li>Auditable policy decisions</li></ul></section> : <EmptyDetails icon="♧">Select a user to view their role details.</EmptyDetails>}</div></div>;
}

function AssetsPage({ notify }) {
  const [assets, setAssets] = useState(initialAssets); const [category, setCategory] = useState('All'); const [register, setRegister] = useState(false); const [form, setForm] = useState({ name: '', category: 'Device', sensitivity: 'Medium', department: '', description: '' });
  const shown = category === 'All' ? assets : assets.filter((asset) => asset.category === category); const submit = (event) => { event.preventDefault(); const item = { id: `ASSET-${String(assets.length + 1).padStart(3, '0')}`, name: form.name, category: form.category, sensitivity: form.sensitivity, owner: 'Current workspace', state: 'Pending' }; setAssets([item, ...assets]); setRegister(false); notify(`${item.name} registered. Minting evidence is queued for protected processing.`); };
  return <div className="common-workspace"><PageHead eyebrow="DIGITAL ASSET REGISTRY" title="Digital Assets" action={<Button className="primary" onClick={() => setRegister(true)}><Glyph>＋</Glyph>Register Asset</Button>}>Manage and track registered enterprise assets.</PageHead><div className="filter-buttons asset-filters">{['All', 'Defence Equipment', 'Device', 'Enterprise Document', 'Certificate', 'Software License'].map((item) => <Button key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)}>{item}</Button>)}</div><section className="common-card table-card"><table className="common-table assets-table"><thead><tr><th>Asset</th><th>Category</th><th>Sensitivity</th><th>Owner</th><th>Evidence</th><th>Status</th><th>Actions</th></tr></thead><tbody>{shown.map((asset) => <tr key={asset.id}><td><Glyph>◇</Glyph><b>{asset.name}</b><small>{asset.id}</small></td><td>{asset.category}</td><td><Pill tone={asset.sensitivity.toLowerCase()}>{asset.sensitivity}</Pill></td><td>{asset.owner}</td><td><span className="safe-code">Protected record · {safeReference(asset.id)}</span></td><td><Pill tone={asset.state === 'Active' ? 'success' : 'pending'}>{asset.state}</Pill></td><td>{asset.state === 'Pending' && <Button onClick={() => notify(`${asset.name} is now queued for minting.`)}>◈ Mint</Button>}<Button onClick={() => notify(`Opened privacy-safe passport for ${asset.name}.`)}>Passport</Button></td></tr>)}</tbody></table></section>{register && <Modal title="Register New Asset" onClose={() => setRegister(false)}><form className="common-form" onSubmit={submit}><label>Asset name *<input required placeholder="e.g. Radar Control Unit" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Category<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{['Defence Equipment', 'Device', 'Enterprise Document', 'Certificate', 'Software License'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Sensitivity<select value={form.sensitivity} onChange={(e) => setForm({ ...form, sensitivity: e.target.value })}>{['Low', 'Medium', 'High', 'Critical'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Department<input placeholder="e.g. Defence Systems" value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} /></label><label>Description<textarea placeholder="Brief description of the asset" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><footer><Button onClick={() => setRegister(false)}>Cancel</Button><Button className="primary" type="submit">Register Asset</Button></footer></form></Modal>}</div>;
}

function PassportPage() {
  const [assetId, setAssetId] = useState('ASSET-001'); const asset = initialAssets.find((item) => item.id === assetId) || initialAssets[0];
  return <div className="common-workspace"><PageHead eyebrow="ASSET PASSPORT" title={asset.name}>Complete lifecycle record for this specific asset.</PageHead><div className="filter-buttons asset-selector">{initialAssets.map((item) => <Button className={item.id === assetId ? 'active' : ''} onClick={() => setAssetId(item.id)} key={item.id}>{item.id}</Button>)}</div><div className="passport-grid"><section className="common-card passport-facts"><div className="asset-name"><Glyph>◇</Glyph><div><h3>{asset.name}</h3><p>{asset.category}</p></div></div>{[['Asset ID', asset.id], ['Evidence', `Protected record · ${safeReference(asset.id)}`], ['Current owner', asset.owner], ['Custody proof', 'Backend protected'], ['Department', 'Defence Systems'], ['Sensitivity', asset.sensitivity], ['Registry status', 'Recorded ✓'], ['Verification', 'Verified ✓']].map(([label, value]) => <div className="passport-fact" key={label}><span>{label}</span><b>{value}</b></div>)}<p className="passport-description">Controlled enterprise asset record. Underlying identifiers and cryptographic proofs remain inside protected services.</p></section><section className="common-card lifecycle"><h3>Asset Lifecycle</h3>{stages.map((stage, index) => <div className={index < 2 ? 'life-step complete' : 'life-step'} key={stage}><span>{index < 2 ? (index === 0 ? '▣' : '◆') : '•'}</span><div><b>{stage}</b><p>{index === 0 ? 'Asset registered in BEL TrustGrid' : index === 1 ? 'Custody evidence recorded' : stage === 'Current Owner' ? 'Active custodian confirmed' : 'Recorded when the controlled action occurs'}</p>{index === 0 && <small>27 Sept, 10:16 pm · Protected evidence</small>}</div></div>)}</section></div></div>;
}

function AccessRequestsPage({ notify }) {
  const [requests, setRequests] = useState(initialRequests); const [filter, setFilter] = useState('All'); const [selected, setSelected] = useState(null); const shown = filter === 'All' ? requests : requests.filter((request) => request.status === filter);
  const decide = (id, status) => { setRequests((items) => items.map((item) => item.id === id ? { ...item, status } : item)); setSelected((item) => item?.id === id ? { ...item, status } : item); notify(`${id} marked ${status.toLowerCase()} and added to the protected audit queue.`); };
  return <div className="common-workspace"><PageHead eyebrow="CONTROLLED ACCESS" title="Access Requests" action={<div className="filter-buttons">{['All', 'Pending', 'Approved', 'Denied'].map((item) => <Button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</Button>)}</div>}>Manage pending and historical access requests.</PageHead><section className="dual-approval"><Glyph>△</Glyph><div><b>Two-Person Authorization Required</b><p>Critical asset requests require two authorized approvals. The second pending approval is highlighted for review.</p></div></section><div className="two-panel"><section className="common-card table-card"><table className="common-table request-table"><thead><tr><th>Requester</th><th>Asset</th><th>Action</th><th>Duration</th><th>Risk</th><th>Status</th><th>Decision</th></tr></thead><tbody>{shown.map((request) => <tr key={request.id} onClick={() => setSelected(request)}><td><b>{request.requester}</b><small>{request.id}</small></td><td>{request.asset}</td><td>{request.action}</td><td>{request.duration}</td><td><Pill tone={request.risk.toLowerCase()}>{request.risk}</Pill></td><td><Pill tone={request.status.toLowerCase()}>{request.status}</Pill></td><td>{request.status === 'Pending' && <><Button className="approve" onClick={(event) => { event.stopPropagation(); decide(request.id, 'Approved'); }}>✓</Button><Button className="deny" onClick={(event) => { event.stopPropagation(); decide(request.id, 'Denied'); }}>×</Button></>}</td></tr>)}</tbody></table></section>{selected ? <section className="common-card selected-detail"><h3>{selected.id}</h3><p>{selected.requester} requests <b>{selected.action}</b> access to {selected.asset}.</p><Pill tone={selected.status.toLowerCase()}>{selected.status}</Pill><hr /><small>Reason</small><p>Operational need validated against least-privilege policy.</p></section> : <EmptyDetails icon="▣">Select a request to view details.</EmptyDetails>}</div></div>;
}

function PermissionsPage({ notify }) {
  const [permissions, setPermissions] = useState(initialPermissions); const [filter, setFilter] = useState('All'); const [grant, setGrant] = useState(false); const [form, setForm] = useState({ user: people[0].name, asset: initialAssets[0].name, permission: 'View', until: '' }); const shown = filter === 'All' ? permissions : permissions.filter((item) => item.status === filter);
  const revoke = (id) => { setPermissions((items) => items.map((item) => item.id === id ? { ...item, status: 'Revoked' } : item)); notify(`${id} revoked and recorded for policy review.`); };
  const submit = (event) => { event.preventDefault(); const person = people.find((item) => item.name === form.user); const item = { id: `PERM-${String(permissions.length + 1).padStart(3, '0')}`, user: form.user, role: person.role, asset: form.asset, permission: form.permission, status: 'Active', grantedBy: 'Current workspace', until: form.until || '31 Dec 2026' }; setPermissions([item, ...permissions]); setGrant(false); notify(`Permission granted to ${form.user}; policy evidence has been queued.`); };
  return <div className="common-workspace"><PageHead eyebrow="AUTHORIZATION MANAGEMENT" title="Permissions" action={<Button className="primary" onClick={() => setGrant(true)}><Glyph>＋</Glyph>Grant Permission</Button>}>Current permission assignments across controlled assets.</PageHead><div className="filter-buttons">{['All', 'Active', 'Revoked', 'Expired'].map((item) => <Button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</Button>)}</div><section className="common-card table-card"><table className="common-table"><thead><tr><th>User</th><th>Role</th><th>Asset</th><th>Permission</th><th>Status</th><th>Granted by</th><th>Valid until</th><th>Actions</th></tr></thead><tbody>{shown.map((permission) => <tr key={permission.id}><td><b>{permission.user}</b><small>{permission.id}</small></td><td>{permission.role}</td><td>{permission.asset}</td><td><Pill>{permission.permission}</Pill></td><td><Pill tone={permission.status.toLowerCase()}>{permission.status}</Pill></td><td>{permission.grantedBy}</td><td>{permission.until}</td><td>{permission.status === 'Active' && <Button className="revoke" onClick={() => revoke(permission.id)}>× Revoke</Button>}</td></tr>)}</tbody></table></section>{grant && <Modal title="Grant Permission" onClose={() => setGrant(false)}><form className="common-form" onSubmit={submit}><label>User<select value={form.user} onChange={(e) => setForm({ ...form, user: e.target.value })}>{people.map((person) => <option key={person.employee}>{person.name}</option>)}</select></label><label>Asset<select value={form.asset} onChange={(e) => setForm({ ...form, asset: e.target.value })}>{initialAssets.map((asset) => <option key={asset.id}>{asset.name}</option>)}</select></label><label>Permission type<select value={form.permission} onChange={(e) => setForm({ ...form, permission: e.target.value })}>{['View', 'Read', 'Modify', 'Approve'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Valid until<input type="date" value={form.until} onChange={(e) => setForm({ ...form, until: e.target.value })} /></label><footer><Button onClick={() => setGrant(false)}>Cancel</Button><Button className="primary" type="submit">✓ Grant</Button></footer></form></Modal>}</div>;
}

function TemporaryAccessPage() { const records = [{ user: 'Rahul Gupta', asset: 'Q3 Procurement Clearance Doc', permission: 'Read', granted: 'Priya Nair', expires: '29 Sept, 10:56 pm' }, { user: 'Sita Reddy', asset: 'ERP Suite License', permission: 'Modify', granted: 'Arjun Sharma', expires: '29 Sept, 09:26 pm' }]; return <div className="common-workspace"><PageHead eyebrow="EXPIRY-AWARE ACCESS" title="Temporary Access">Time-bound permissions with automatic expiry tracking.</PageHead><div className="temporary-stats">{[['◷', '0', 'Active', 'success'], ['△', '0', 'Expiring Soon', 'warning'], ['◷', '2', 'Expired', ''], ['◷', '0', 'Revoked', 'danger']].map(([icon, value, label, tone]) => <section className={`common-card ${tone}`} key={label}><Glyph>{icon}</Glyph><strong>{value}</strong><small>{label}</small></section>)}</div><section className="common-card temporary-list"><header><h3>◷ Time-Limited Permissions</h3><span>Auto-expires when timer reaches end</span></header>{records.map((record) => <article key={record.user}><div className="avatar">{record.user[0]}</div><div className="temporary-title"><b>{record.user}</b><span>{record.asset}</span></div><Pill>EXPIRED</Pill><div className="temporary-meta"><div><small>Permission</small><b>{record.permission}</b></div><div><small>Granted by</small><b>{record.granted}</b></div><div><small>Expires</small><b>{record.expires}</b></div></div><i className="expiry-bar" /><small>Expired</small></article>)}</section></div>; }

function VerificationPage({ notify }) {
  const tabs = ['Identity Verification', 'Asset Ownership', 'Permission Check', 'Authorization Proof']; const [tab, setTab] = useState(tabs[0]); const [ran, setRan] = useState(false); const labels = { 'Identity Verification': 'User / employee', 'Asset Ownership': 'Asset', 'Permission Check': 'User and asset', 'Authorization Proof': 'Controlled action' };
  const run = () => { setRan(true); notify(`${tab} completed. The cryptographic proof remains protected by backend services.`); };
  return <div className="common-workspace"><PageHead eyebrow="CRYPTOGRAPHIC ASSURANCE" title="Verification Center">Verify identity claims, asset ownership, and authorization proofs.</PageHead><div className="verify-tabs">{tabs.map((item, index) => <Button className={tab === item ? 'active' : ''} onClick={() => { setTab(item); setRan(false); }} key={item}><Glyph>{['♙', '◇', '♢', '▣'][index]}</Glyph>{item}</Button>)}</div><div className="verification-grid"><section className="common-card verification-form"><h3>Verification Parameters</h3><label>{labels[tab]}<select><option>{tab === 'Asset Ownership' ? 'Radar Control Module MK-IV — ASSET-001' : 'Arjun Sharma — BEL-001'}</option>{tab === 'Permission Check' && <option>Priya Nair — Radar Control Module MK-IV</option>}</select></label><Button className="primary verify-run" onClick={run}><Glyph>⌕</Glyph>Run Verification</Button></section><section className={`common-card verification-result ${ran ? 'complete' : ''}`}>{ran ? <><Glyph>✓</Glyph><h3>{tab} verified</h3><p>All required claims, policy checks, and signed evidence are valid for the selected record.</p><Pill tone="success">Verified</Pill></> : <><Glyph>♢</Glyph><p>Set the verification parameters and click “Run Verification” to get a cryptographic proof.</p></>}</section></div></div>;
}

function AuditPage() { const [query, setQuery] = useState(''); const [status, setStatus] = useState('All'); const shown = auditEvents.filter((event) => (status === 'All' || event[3] === status) && event.join(' ').toLowerCase().includes(query.toLowerCase())); const success = auditEvents.filter((event) => event[3] === 'Success').length; const failed = auditEvents.filter((event) => event[3] === 'Failed').length; return <div className="common-workspace"><PageHead eyebrow="IMMUTABLE ACTIVITY RECORD" title="Audit Trail">Complete chronological record of all system events.</PageHead><div className="audit-summary"><section className="common-card"><strong>{auditEvents.length + 4}</strong><span>Total Events</span></section><section className="common-card success"><strong>{success + 4}</strong><span>Successful</span></section><section className="common-card danger"><strong>{failed}</strong><span>Failed</span></section><section className="common-card warning"><strong>0</strong><span>Pending</span></section></div><div className="audit-filters"><label><Glyph>⌕</Glyph><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search actor, target, event…" /></label><select value={status} onChange={(e) => setStatus(e.target.value)}><option>All</option><option>Success</option><option>Failed</option></select></div><section className="common-card audit-log"><header><h3>▤ Event Log — {shown.length} events</h3></header>{shown.map(([action, actor, target, result, time, icon]) => <article key={`${action}-${time}`}><span className={result === 'Success' ? 'success' : 'danger'}>{icon}</span><div><h3>{action} <small>· {actor}</small></h3><p>Target: {target} <b>·</b> Protected evidence reference</p><small>{time} · backend-protected proof</small></div><Pill tone={result === 'Success' ? 'success' : 'danger'}>{result}</Pill></article>)}{!shown.length && <p className="common-no-results">No matching events found.</p>}</section></div>; }

function BlockchainPage() {
  const transactions = [['Identity Created', 'Confirmed', 'Identity profile registered', 'Identity Registry', 'Identity record', '25 Sept, 08:16 pm'], ['Asset Registered', 'Confirmed', 'Asset custody record created', 'Asset Registry', 'ASSET-001', '27 Sept, 10:16 pm'], ['Asset Assigned', 'Confirmed', 'Controlled allocation recorded', 'Asset Registry', 'ASSET-002', '28 Sept, 09:36 pm'], ['Permission Updated', 'Confirmed', 'Access policy decision stored', 'RBAC policy', 'PERM-002', '29 Sept, 09:16 am']];
  const flow = [['♙', 'Authorised Users', 'Start a controlled portal action', 'actor'], ['◇', 'TrustGrid Portal', 'Checks role and required business context', 'app'], ['▣', 'Secure API + Policy', 'Applies approval and least-privilege rules', 'service'], ['♢', 'Smart Contract Layer', 'Records identity, asset, and policy events', 'contract'], ['⛓', 'Blockchain Ledger', 'Keeps tamper-resistant evidence history', 'ledger']];
  return <div className="common-workspace"><PageHead eyebrow="ON-CHAIN EVIDENCE" title="Blockchain Activity">A simple view of how a controlled portal action becomes protected blockchain evidence.</PageHead><div className="chain-summary">{[['Latest block', '#18,999,101', ''], ['Total transactions', '6', ''], ['Confirmed', '5', 'success'], ['Pending', '1', 'warning']].map(([label, value, tone]) => <section className={`common-card ${tone}`} key={label}><small>{label}</small><strong>{value}</strong></section>)}</div><div className="blockchain-grid"><section className="common-card contract-network"><header className="blockchain-flow-heading"><h3>How evidence flows</h3><p>One clear path from user action to immutable record.</p></header><div className="simple-chain-flow">{flow.map(([icon, title, detail, tone], index) => <div className="simple-chain-step" key={title}><article className={tone}><Glyph>{icon}</Glyph><div><b>{title}</b><span>{detail}</span></div></article>{index < flow.length - 1 && <i aria-hidden="true">↓</i>}</div>)}</div><ul><li><i className="actor" />User / actor</li><li><i className="app" />TrustGrid application</li><li><i className="contract" />Protected service or contract</li><li><i className="ledger" />Ledger evidence</li></ul></section><section className="common-card transaction-list"><header><h3>〽 Recent Transactions</h3></header>{transactions.map(([type, state, detail, to, resource, time], index) => <article key={type}><div><Pill tone={`transaction ${index}`}>{type}</Pill> <Pill tone="success">{state}</Pill></div><b className="safe-code">Protected record · {String(index + 1).padStart(3, '0')}</b><div className="transaction-meta"><span><small>From</small>Authorised service</span><span><small>To</small>{to}</span><span><small>Asset / scope</small>{resource}</span></div><small>{time}</small></article>)}</section></div></div>;
}

function SecurityPage({ notify }) { const [showAcknowledged, setShowAcknowledged] = useState(false); const [alerts, setAlerts] = useState([{ title: 'Repeated Denied Access', description: '5 consecutive denied access attempts on Missile Guidance Subsystem from an unrecognised request.', actor: 'Unknown actor', target: 'ASSET-006', severity: 'Critical', acknowledged: false }, { title: 'Suspicious Transfer Attempt', description: 'Unauthorised ownership transfer attempt on ASSET-005 by an inactive user account.', actor: 'Rahul Gupta', target: 'ASSET-005', severity: 'High', acknowledged: false }, { title: 'Unusual Access Attempt', description: 'Asset accessed from an unregistered context outside business hours.', actor: 'Unknown actor', target: 'ASSET-003', severity: 'High', acknowledged: false }]); const visible = showAcknowledged ? alerts : alerts.filter((item) => !item.acknowledged); const acknowledge = (title) => { setAlerts((items) => items.map((item) => item.title === title ? { ...item, acknowledged: true } : item)); notify(`${title} acknowledged; it remains in the protected review history.`); };
  return <div className="common-workspace"><PageHead eyebrow="THREAT DETECTION" title="Security Insights" action={<Button onClick={() => setShowAcknowledged(!showAcknowledged)}><Glyph>◉</Glyph>{showAcknowledged ? 'Hide Acknowledged' : 'Show Acknowledged'}</Button>}>Suspicious and high-risk activity requiring attention.</PageHead><div className="security-stats">{[['Critical', 1, 'critical'], ['High', 2, 'high'], ['Medium', 0, 'medium'], ['Low', 0, 'low']].map(([label, count, tone]) => <section className="common-card" key={label}><i className={tone} /><strong>{count}</strong><span>{label}</span></section>)}</div><div className="alert-list">{visible.map((alert) => <article key={alert.title} className={alert.acknowledged ? 'acknowledged' : ''}><i /><div><h3>{alert.title}</h3><p>{alert.description}</p><small>Actor: <b>{alert.actor}</b> · Target: <b>{alert.target}</b> · 29 Sept, 08:41 pm</small></div><Pill tone={alert.severity.toLowerCase()}>{alert.severity}</Pill>{!alert.acknowledged && <Button className="acknowledge" onClick={() => acknowledge(alert.title)}>Acknowledge</Button>}<Glyph>△</Glyph></article>)}{!visible.length && <p className="common-no-results">No alerts in this view.</p>}</div></div>; }

function ArchitecturePage() { const contracts = [['▣', 'DID Identity Layer', 'W3C DID · Decentralized Identifiers · Credential Proofs'], ['♢', 'RBAC Authorization Layer', 'Role-Based Access Control · Smart Contract Enforcement'], ['◇', 'Digital Asset / NFT Layer', 'Asset Tokenization · Controlled Token Registry'], ['▤', 'Smart Contract Layer', 'Policy Rules · Automated Controls · Event Emission']]; return <div className="common-workspace"><PageHead eyebrow="TRUSTGRID TECHNICAL MAP" title="System Architecture">TrustGrid technical architecture and component relationships.</PageHead><div className="architecture-layout"><div className="architecture-stack"><section className="architecture-layer users-layer"><Glyph>♙</Glyph><div><h3>Users</h3><p>Admin · Manager · Auditor · User</p></div></section><span className="architecture-arrow">↓</span><section className="architecture-layer web-layer"><Glyph>◇</Glyph><div><h3>BEL TRUSTGRID WEB APPLICATION</h3><p>React + Vite · Role-Based Dashboard · Secure UI</p></div></section><span className="architecture-arrow">↓</span><section className="architecture-layer api-layer"><Glyph>▣</Glyph><div><h3>Authentication + Backend / API</h3><p>Protected credential verification · Session management · Secure APIs</p></div></section><span className="architecture-arrow">↓</span><section className="contracts-layer"><h3>BLOCKCHAIN CONTRACT LAYER</h3><div>{contracts.map(([icon, title, description]) => <article key={title}><Glyph>{icon}</Glyph><div><b>{title}</b><p>{description}</p></div></article>)}</div></section><span className="architecture-arrow">↓</span><section className="architecture-layer ledger-layer"><Glyph>⛓</Glyph><div><h3>BLOCKCHAIN LEDGER</h3><p>Ethereum-Compatible · Tamper-Resistant Records · Immutable History</p></div></section></div><aside className="architecture-aside"><section className="common-card"><h3>Off-Chain Components</h3>{[['▣', 'Encrypted Off-Chain Storage', 'Sensitive data stored as protected references'], ['▦', 'Existing Enterprise Systems', 'ERP · HR · Procurement integration'], ['⌁', 'API Integration Layer', 'BEL backend systems · Secure REST APIs']].map(([icon, title, desc]) => <article className="architecture-note" key={title}><Glyph>{icon}</Glyph><div><b>{title}</b><p>{desc}</p></div></article>)}</section><section className="common-card"><h3>Blockchain Scope</h3>{['Tamper-resistant records', 'Independent verification', 'Shared trusted history', 'Ownership history', 'Permission change log', 'Physical asset security', 'Data accuracy guarantee'].map((item, index) => <p className={index > 4 ? 'disabled' : ''} key={item}>{index > 4 ? '×' : '✓'} {item}</p>)}</section></aside></div></div>; }

function ScopedNotice({ title, children, action }) { return <div className="common-workspace scoped-workspace"><PageHead eyebrow="PERSONAL, LEAST-PRIVILEGE VIEW" title={title} action={action}>{children}</PageHead><section className="common-card scoped-notice"><Glyph>◈</Glyph><div><h3>Protected personal workspace</h3><p>Only records needed for your assigned work are visible here. Identifiers, evidence, and other users’ information stay in protected services.</p></div></section></div>; }

function RequestAccessButton({ onNavigate, label = 'Request Access' }) { return <Button className="primary" onClick={() => onNavigate?.('access-requests')}><Glyph>＋</Glyph>{label}</Button>; }

function ProjectAssignmentStrip({ context }) {
  const assignments = context?.assignments || [];
  const grants = context?.grants || [];
  if (!assignments.length) return null;
  return <section className="common-card role-project-context"><header><div><p>ROLE-SPECIFIC DEMO DATA</p><h3>My project assignments and access grants</h3></div><Pill tone="success">{assignments.length} assigned</Pill></header><div className="role-project-grid">{assignments.map((item) => <article key={`${item.projectId}-${item.taskTitle}`}><div className="role-project-heading"><span>{item.projectCode}</span><Pill tone={item.grantStatus === 'PENDING' ? 'pending' : 'success'}>{item.grantStatus}</Pill></div><h4>{item.projectName}</h4><p>{item.relationship} · {item.workstream}</p><strong>{item.taskTitle}</strong><small>Task status: {item.taskStatus} · Access: {item.accessLevel}</small></article>)}</div>{grants.length > 0 && <div className="role-grant-summary"><b>Access request history</b>{grants.slice(0, 3).map((grant) => <span key={grant.requestId}>{grant.requestedPermission} {grant.requestedModule} · {grant.status}</span>)}</div>}</section>;
}

function EmployeeIdentityPage({ user, notify }) {
  const [requestOpen, setRequestOpen] = useState(false);
  const [reason, setReason] = useState('');
  const submitRequest = (event) => {
    event.preventDefault();
    setRequestOpen(false);
    notify?.('Your DID request was submitted for administrator verification. No identity is created until it is approved.');
  };
  return <><ScopedNotice title="My Identity" action={<Button className="primary" onClick={() => setRequestOpen(true)}><Glyph>＋</Glyph>Request DID</Button>}>View the verified identity profile for your own workspace. A DID request is reviewed and created only by an administrator.</ScopedNotice><section className="common-card scoped-profile"><span className="large-initial">{(user?.fullName || 'U')[0]}</span><div><h2>{user?.fullName || 'Authorised employee'}</h2><p>{user?.employeeId || 'Protected employee reference'} · {user?.department || 'Assigned department'}</p><Pill tone="success">Identity status checked</Pill></div><aside><small>Identity workflow</small><b>Request → administrator verification → protected DID creation</b></aside></section>{requestOpen && <Modal title="Request a DID" onClose={() => setRequestOpen(false)}><form className="common-form" onSubmit={submitRequest}><label>Official name<input required value={user?.fullName || ''} readOnly /></label><label>Employee ID<input required value={user?.employeeId || ''} readOnly /></label><label>Department<input required value={user?.department || ''} readOnly /></label><label>Business reason<textarea required placeholder="Explain why you need a DID for your authorised work" value={reason} onChange={(event) => setReason(event.target.value)} /></label><p className="scope-caption">An administrator reviews this request before a protected DID is created. No wallet, DID, or credential value is entered here.</p><footer><Button onClick={() => setRequestOpen(false)}>Cancel</Button><Button className="primary" type="submit">Submit for approval</Button></footer></form></Modal>}</>;
}

function EmployeeUsersPage({ user }) { return <div className="common-workspace scoped-workspace"><PageHead eyebrow="PERSONAL ACCESS PROFILE" title="Users & Roles">Your role is assigned by an administrator and cannot be changed from an employee portal.</PageHead><section className="common-card scoped-profile"><span className="large-initial">{(user?.fullName || 'U')[0]}</span><div><h2>{user?.fullName || 'Authorised employee'}</h2><p>{user?.department || 'Assigned department'} · {user?.role || 'Employee'}</p><Pill tone="success">Active</Pill> <Pill>{user?.role || 'Employee'}</Pill></div><aside><small>Access model</small><b>Request → admin approval → time-bound grant</b></aside></section><section className="common-card scoped-list"><h3>Authorised capabilities</h3><p>✓ View records explicitly granted to you</p><p>✓ Submit access and permission requests with a business justification</p><p>✓ Verify your own identity and assigned-record proof</p><p className="restricted">× Manage other users, roles, permissions, or security incidents</p></section></div>; }

function EmployeeAssetsPage({ onNavigate, projectContext }) {
  const assets = (projectContext?.assignments || []).map((assignment) => ({ id: assignment.projectCode, name: assignment.projectName, category: assignment.workstream, sensitivity: assignment.projectStatus, access: assignment.grantStatus === 'PENDING' ? 'Approval pending' : `${assignment.accessLevel} granted` }));
  return <div className="common-workspace scoped-workspace"><PageHead eyebrow="AUTHORISED ASSET VIEW" title="Digital Assets" action={<RequestAccessButton onNavigate={onNavigate} label="Request Asset Access" />}>Project records are limited to your role assignment and the access grant approved for that work.</PageHead><section className="common-card table-card"><table className="common-table"><thead><tr><th>Project record</th><th>Workstream</th><th>Project status</th><th>Access</th></tr></thead><tbody>{assets.length ? assets.map((asset) => <tr key={asset.id}><td><b>{asset.name}</b><small>{asset.id} · Protected project reference</small></td><td>{asset.category}</td><td><Pill>{asset.sensitivity}</Pill></td><td><Pill tone={asset.access === 'Approval pending' ? 'pending' : 'success'}>{asset.access}</Pill></td></tr>) : <tr><td colSpan="4">No project records are assigned to this role.</td></tr>}</tbody></table></section><p className="scope-caption">Other projects, asset owners, custody transfers, and protected evidence are unavailable until an administrator grants a justified, time-bound permission.</p></div>;
}

function EmployeePassportPage({ projectContext }) { const assignment = projectContext?.assignments?.[0]; const record = { title: assignment?.projectName || 'Assigned project record', category: assignment?.workstream || 'Authorised workstream', issued: '30 Sept 2026', status: assignment?.grantStatus || 'No grant recorded', scope: assignment ? `${assignment.projectCode} · ${assignment.relationship}` : 'Role-specific project scope' }; return <div className="common-workspace scoped-workspace"><PageHead eyebrow="AUTHORISED RECORD LIFECYCLE" title="Asset Passport">This lifecycle describes only the project record tied to your role assignment; unrelated asset evidence remains protected.</PageHead><div className="passport-grid"><section className="common-card passport-facts"><div className="asset-name"><Glyph>◇</Glyph><div><h3>{record.title}</h3><p>{record.category} · Fictional role demo</p></div></div>{[['Record scope', record.scope], ['Access state', record.status], ['Passport issued', record.issued], ['Integrity state', 'Protected verification available'], ['Task', assignment?.taskTitle || 'No active task']].map(([label, value]) => <div className="passport-fact" key={label}><span>{label}</span><b>{value}</b></div>)}<p className="passport-description">This mock passport is generated from your current demo assignment without revealing other project owners, evidence, or cryptographic identifiers.</p></section><section className="common-card lifecycle"><h3>Asset Lifecycle</h3>{stages.map((stage, index) => <div className={index < 3 ? 'life-step complete' : 'life-step'} key={stage}><span>{index < 3 ? '✓' : '•'}</span><div><b>{stage}</b><p>{index === 0 ? 'Role-specific project record registered' : index === 1 ? 'Protected evidence reference issued' : index === 2 ? `${record.status} access grant checked` : 'Shown when your approved work requires it'}</p>{index < 3 && <small>{['27 Sept, 10:16 am', '28 Sept, 02:35 pm', '30 Sept, 09:12 am'][index]} · Demo evidence</small>}</div></div>)}</section></div></div>; }

function EmployeePermissionsPage({ onNavigate, projectContext }) {
  const permissions = projectContext?.assignments || [];
  return <div className="common-workspace scoped-workspace"><PageHead eyebrow="MY AUTHORISATION" title="Permissions" action={<RequestAccessButton onNavigate={onNavigate} label="Request Permission" />}>You can request only the minimum permission required for your assigned task. Administrators remain the grant, revoke, and extension authority.</PageHead><section className="common-card table-card"><table className="common-table"><thead><tr><th>Project scope</th><th>Permission</th><th>Status</th><th>Task context</th></tr></thead><tbody>{permissions.length ? permissions.map((item) => <tr key={`${item.projectId}-${item.taskTitle}`}><td><b>{item.projectName}</b><small>{item.projectCode} · {item.workstream}</small></td><td><Pill>{item.accessLevel}</Pill></td><td><Pill tone={item.grantStatus === 'PENDING' ? 'pending' : 'success'}>{item.grantStatus}</Pill></td><td>{item.taskTitle}<small>{item.taskStatus}</small></td></tr>) : <tr><td colSpan="4">No permissions are assigned to this role.</td></tr>}</tbody></table></section><section className="common-card scoped-policy"><h3>Least-privilege policy</h3><p>Each request needs a stated operational purpose, expires automatically, and remains in the protected audit trail. Project access never implies access to other departments’ records.</p></section></div>;
}

function EmployeeTemporaryAccessPage({ onNavigate, projectContext }) { const grants = projectContext?.grants || []; return <div className="common-workspace scoped-workspace"><PageHead eyebrow="TIME-BOUND ACCESS" title="Temporary Access" action={<RequestAccessButton onNavigate={onNavigate} label="Request Time-Bound Access" />}>Time-bound access is granted only after administrator approval and ends automatically at its expiry time.</PageHead><section className="common-card scoped-list"><h3>My access requests</h3>{grants.length ? grants.map((grant) => <p key={grant.requestId}><b>{grant.requestedPermission} {grant.requestedModule}</b> · {grant.businessReason} <Pill tone={grant.status === 'PENDING' ? 'pending' : grant.status === 'APPROVED' ? 'success' : ''}>{grant.status}</Pill></p>) : <p>No additional time-bound access requests have been recorded for this role.</p>}</section></div>; }

function EmployeeVerificationPage({ user, notify }) { const [ran, setRan] = useState(false); const run = () => { setRan(true); notify('Your identity assurance check completed. The proof remains protected by backend services.'); }; return <div className="common-workspace scoped-workspace"><PageHead eyebrow="PERSONAL CRYPTOGRAPHIC ASSURANCE" title="Verification Center">Run a verification only for your own identity and authorised work context.</PageHead><div className="verification-grid"><section className="common-card verification-form"><h3>My verification parameters</h3><label>Authorised profile<select value="self" readOnly><option>{user?.fullName || 'Current employee'} — personal profile</option></select></label><Button className="primary verify-run" onClick={run}><Glyph>⌕</Glyph>Run Verification</Button></section><section className={`common-card verification-result ${ran ? 'complete' : ''}`}>{ran ? <><Glyph>✓</Glyph><h3>Personal identity verified</h3><p>Required role and policy checks are valid. Detailed cryptographic evidence is never exposed in this portal.</p><Pill tone="success">Verified</Pill></> : <><Glyph>♢</Glyph><p>Run a personal verification to validate the secure access context for this session.</p></>}</section></div></div>; }

function EmployeeAuditPage() { const events = [['Access request submitted', 'Awaiting administrator decision', 'Pending'], ['Identity assurance checked', 'Personal policy proof verified', 'Success']]; return <div className="common-workspace scoped-workspace"><PageHead eyebrow="PERSONAL ACTIVITY RECORD" title="Audit Trail">Your portal actions are recorded without exposing enterprise-wide activity.</PageHead><section className="common-card audit-log"><header><h3>▤ My event log</h3></header>{events.map(([title, detail, state], index) => <article key={title}><span className={state === 'Success' ? 'success' : ''}>{index ? '✓' : '◷'}</span><div><h3>{title}</h3><p>{detail}</p><small>Protected evidence reference · Current session</small></div><Pill tone={state === 'Success' ? 'success' : 'pending'}>{state}</Pill></article>)}</section></div>; }

function EmployeeBlockchainPage() { const flow = [['♙', 'Your request', 'Employee submits a justified request'], ['▣', 'Policy review', 'Administrator checks role and business purpose'], ['♢', 'Secure contract event', 'Approved decision is recorded'], ['⛓', 'Evidence history', 'Protected ledger preserves the result']]; return <div className="common-workspace scoped-workspace"><PageHead eyebrow="PROTECTED EVIDENCE FLOW" title="Blockchain Activity">A simple view of how your approved action becomes tamper-resistant evidence.</PageHead><section className="common-card contract-network"><header className="blockchain-flow-heading"><h3>Approval to evidence</h3><p>Personal activity is shown as a workflow, never as a raw identifier.</p></header><div className="simple-chain-flow">{flow.map(([icon, title, detail], index) => <div className="simple-chain-step" key={title}><article className={index === 0 ? 'actor' : index === flow.length - 1 ? 'ledger' : 'contract'}><Glyph>{icon}</Glyph><div><b>{title}</b><span>{detail}</span></div></article>{index < flow.length - 1 && <i aria-hidden="true">↓</i>}</div>)}</div></section></div>; }

function EmployeeSecurityPage() { return <div className="common-workspace scoped-workspace"><PageHead eyebrow="PERSONAL SECURITY POSTURE" title="Security Insights">Enterprise signals are handled by the security administration team; only actions relevant to your account are displayed here.</PageHead><section className="common-card security-private"><Glyph>♢</Glyph><div><h3>No personal security action required</h3><p>Security monitoring is active. You will be notified if an administrator needs you to verify a request or session.</p></div><Pill tone="success">Protected</Pill></section><section className="common-card scoped-policy"><h3>What stays protected</h3><p>Other employees’ events, security investigations, asset identifiers, and incident evidence are intentionally not exposed in this portal.</p></section></div>; }

function EmployeeWorkspace({ module, user, notify, onNavigate, projectContext }) {
  const pages = {
    identity: <EmployeeIdentityPage user={user} notify={notify} />,
    users: <EmployeeUsersPage user={user} />,
    'digital-assets': <EmployeeAssetsPage onNavigate={onNavigate} projectContext={projectContext} />,
    'asset-passport-common': <EmployeePassportPage projectContext={projectContext} />,
    permissions: <EmployeePermissionsPage onNavigate={onNavigate} projectContext={projectContext} />,
    'temporary-access': <EmployeeTemporaryAccessPage onNavigate={onNavigate} projectContext={projectContext} />,
    verification: <EmployeeVerificationPage user={user} notify={notify} />,
    'audit-common': <EmployeeAuditPage />,
    'blockchain-activity': <EmployeeBlockchainPage />,
    'security-insights': <EmployeeSecurityPage />,
    'architecture-common': <ArchitecturePage />,
  };
  return <><ProjectAssignmentStrip context={projectContext} />{pages[module] || <EmployeeIdentityPage user={user} notify={notify} />}</>;
}

export function CommonWorkspace({ module, user, notify, onNavigate, projectContext }) {
  const [toast, setToast] = useState(''); const announce = (message) => { setToast(message); notify?.(message); window.setTimeout(() => setToast(''), 4500); };
  const isAdmin = user?.roleKey === 'ERP_ADMIN';
  const pages = { identity: <IdentityPage notify={announce} />, users: <UsersPage />, 'digital-assets': <AssetsPage notify={announce} />, 'asset-passport-common': <PassportPage />, permissions: <PermissionsPage notify={announce} />, 'temporary-access': <TemporaryAccessPage />, verification: <VerificationPage notify={announce} />, 'audit-common': <AuditPage />, 'blockchain-activity': <BlockchainPage />, 'security-insights': <SecurityPage notify={announce} />, 'architecture-common': <ArchitecturePage /> };
  const content = isAdmin ? (pages[module] || <IdentityPage notify={announce} />) : <EmployeeWorkspace module={module} user={user} notify={announce} onNavigate={onNavigate} projectContext={projectContext} />;
  return <>{content}{toast && <div className="common-toast" role="status">✓ {toast}</div>}</>;
}
